{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ default (include "backend.fullname" .) .Values.externalSecret.name }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.secretStore.name }}
  target:
    name: {{ .Values.externalSecret.target.name }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
    deletionPolicy: {{ .Values.externalSecret.target.deletionPolicy }}
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: {{ required "externalSecret.rds.key is required" .Values.externalSecret.rds.key | quote }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.rds.key | quote }}
        property: password
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.application.key | quote }}
        property: JWT_SECRET
{{- end }}
