{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_HOST: {{ .Values.secret.data.DB_HOST | quote }}
  DB_PORT: {{ .Values.secret.data.DB_PORT | quote }}
  DB_NAME: {{ .Values.secret.data.DB_NAME | quote }}
  DB_USERNAME: {{ .Values.secret.data.DB_USERNAME | quote }}
  DB_PASSWORD: {{ .Values.secret.data.DB_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secret.data.JWT_SECRET | quote }}
  JWT_EXPIRATION: {{ .Values.secret.data.JWT_EXPIRATION | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.secret.data.CORS_ALLOWED_ORIGINS | quote }}
{{- end }}
