fullnameOverride: smtm-frontend

image:
  repository: example.invalid/smtm-frontend
  tag: ci

autoscaling:
  enabled: true

podDisruptionBudget:
  enabled: true

ingress:
  enabled: true
  className: alb
  host: smtm.example.invalid
  backendServiceName: smtm-backend
  backendServicePort: 8080
  annotations:
    alb.ingress.kubernetes.io/group.name: smtm
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-name: smtm-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/target-type: ip
